name: Deploy feature branch to S3

on:
  push:
    branches:
      - 'feature-*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Replace the baseurl with this branch
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: 'baseurl: "/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}"'
          replace: 'baseurl: "/${{ env.GITHUB_REF_SLUG }}"'
          include: _config.yml
      - name: Build the site
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install
          bundle exec jekyll build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: open-sdg-feature
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
          SOURCE_DIR: _site
          DEST_DIR: ${{ env.GITHUB_REF_SLUG }}
